import { Link } from 'react-router-dom';
import './LandingPage.css';

export default function LandingPage() {
  return (
    <div className="landing-root">
      <div className="landing-hero">
        <div className="hero-content">
          <h1 className="hero-title">AI Learning Assistant</h1>
          <p className="hero-tagline">Instantly generate lessons and quizzes on any topic. Learn smarter, not harder.</p>
          <Link to="/learn" className="hero-cta">Get Started</Link>
        </div>
        <div className="hero-illustration">
          {/* Friendly AI/Book SVG illustration */}
          <svg width="180" height="180" viewBox="0 0 180 180" fill="none" xmlns="http://www.w3.org/2000/svg">
            <ellipse cx="90" cy="90" rx="90" ry="90" fill="url(#paint0_radial)"/>
            <rect x="45" y="60" width="90" height="60" rx="18" fill="#fff"/>
            <rect x="60" y="75" width="60" height="30" rx="8" fill="#e0e7ff"/>
            <rect x="70" y="85" width="40" height="8" rx="4" fill="#a1c4fd"/>
            <rect x="70" y="100" width="24" height="8" rx="4" fill="#a1c4fd"/>
            <circle cx="120" cy="120" r="10" fill="#a1c4fd"/>
            <rect x="110" y="118" width="20" height="8" rx="4" fill="#c2e9fb"/>
            <defs>
              <radialGradient id="paint0_radial" cx="0" cy="0" r="1" gradientTransform="translate(90 90) rotate(90) scale(90)" gradientUnits="userSpaceOnUse">
                <stop stopColor="#f8fafc"/>
                <stop offset="1" stopColor="#a1c4fd"/>
              </radialGradient>
            </defs>
          </svg>
        </div>
      </div>
      <section className="landing-benefits">
        <h2>Why use AI Learning Assistant?</h2>
        <div className="benefit-cards">
          <div className="benefit-card">
            <span className="benefit-icon">⚡</span>
            <h3>Instant Lessons</h3>
            <p>Get a concise, clear lesson on any topic in seconds.</p>
          </div>
          <div className="benefit-card">
            <span className="benefit-icon">📝</span>
            <h3>Interactive Quizzes</h3>
            <p>Test your knowledge with auto-generated multiple-choice quizzes.</p>
          </div>
          <div className="benefit-card">
            <span className="benefit-icon">🎯</span>
            <h3>Personalized Learning</h3>
            <p>Focus on what you want to learn, at your own pace.</p>
          </div>
          <div className="benefit-card">
            <span className="benefit-icon">🌈</span>
            <h3>Beautiful & Calming</h3>
            <p>Enjoy a distraction-free, visually soothing learning experience.</p>
          </div>
        </div>
      </section>
      <section className="landing-how">
        <h2>How it works</h2>
        <div className="how-steps">
          <div className="how-step">
            <span className="how-icon">🔍</span>
            <p>Enter any topic you want to learn about.</p>
          </div>
          <div className="how-step">
            <span className="how-icon">📚</span>
            <p>Get a short, clear lesson instantly generated by AI.</p>
          </div>
          <div className="how-step">
            <span className="how-icon">✅</span>
            <p>Take a quiz to test your understanding.</p>
          </div>
        </div>
      </section>
      <section className="landing-cta">
        <h2>Ready to start learning?</h2>
        <Link to="/learn" className="hero-cta">Get Started</Link>
      </section>
    </div>
  );
} 